const listMovie = [
  {
    id: 1,
    poster: require('../assets/images/movies/spiderhomecoming.jpg'),
    title: 'Spider-Man: Homecoming',
    genre: 'Adventure, Action, Sci-Fi',
    release: 'June 28, 2017',
    directed: 'Jon Watss',
    duration: '2 hours 13 minutes',
    cast: 'Tom Holland, Michael Keaton, Robert Downey Jr., ...',
    synopsis:
      'Thrilled by his experience with the Avengers, Peter returns home, where he lives with his Aunt May, under the watchful eye of his new mentor Tony Stark, Peter tries to fall back into his normal daily routine - distracted by thoughts of proving himself to be more than just your friendly neighborhood Spider-Man - but when the Vulture emerges as a new villain, everything that Peter holds most important will be threatened.',
  },
  {
    id: 2,
    poster: require('../assets/images/movies/lionking.png'),
    title: 'The Lion King',
    genre: '',
    release: '',
    directed: '',
    duration: '',
    cast: '',
    synopsis: '',
  },
  {
    id: 3,
    poster: require('../assets/images/movies/avengers.jpg'),
    title: 'Avengers: End Game',
    genre: '',
    release: '',
    directed: '',
    duration: '',
    cast: '',
    synopsis: '',
  },
  {
    id: 4,
    poster: require('../assets/images/movies/mazerunner.jpeg'),
    title: 'Maze Runner: Death Cure',
    genre: '',
    release: '',
    directed: '',
    duration: '',
    cast: '',
    synopsis: '',
  },
  {
    id: 5,
    poster: require('../assets/images/movies/trans2.jpg'),
    title: 'Hotel Transylvania 2',
    genre: '',
    release: '',
    directed: '',
    duration: '',
    cast: '',
    synopsis: '',
  },
  {
    id: 6,
    poster: require('../assets/images/movies/antman.jpg'),
    title: 'Ant Man',
    genre: '',
    release: '',
    directed: '',
    duration: '',
    cast: '',
    synopsis: '',
  },
];
export default listMovie;
